### ISSUE TITLE
Error when running settings

### ISSUE THREAD

**Issue by jorgetamayo21** [so1der/m601#2]
I'm getting this error when running sudo python cli.py -r settings

![imagen](https://github.com/so1der/m601/assets/59964898/cdf2d188-21e3-4ab0-8235-bd6ed273d838)

I have the m601-rgb mouse

![imagen](https://github.com/so1der/m601/assets/59964898/3eb3d30c-75e5-4cb9-a1b9-00cb7d0840d3)

I use ubuntu 22.04 and python 3.10.12, I have the udev rules added too

![imagen](https://github.com/so1der/m601/assets/59964898/16751b81-35d4-4e68-ba00-6d396499ce11)

**Comment by so1der** [comment]
Hello!
This error was caused because Your mouse has a keycode that wasn't yet implemented in this script. As far as I can tell, it's a simple HID button that was binded as a key combination. I added keycodes like that into this script, now everything should be fine, so, please, clone the repository again to get a newer version, and try again. Let me know if everything works now!

**Comment by jorgetamayo21** [comment]
The problem is solved, thank you very much!

**Comment by so1der** [comment]
Very glad to hear it! Thank You for contribution :)
